# Generated by Django 3.2 on 2021-05-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(default='null', max_length=100)),
                ('opt1', models.CharField(default='null', max_length=100)),
                ('opt2', models.CharField(default='null', max_length=100)),
                ('opt3', models.CharField(default='null', max_length=100)),
                ('opt4', models.CharField(default='null', max_length=100)),
                ('correct_ans', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
