# Generated by Django 3.2 on 2021-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('createpassword', models.CharField(max_length=12)),
                ('confirmpassword', models.CharField(max_length=12)),
            ],
        ),
    ]
