# Generated by Django 3.2 on 2021-05-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210510_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='correct',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='op1',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='op2',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='op3',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='op4',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='question',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
