# Generated by Django 3.2 on 2021-05-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210510_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='op4',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='question',
        ),
        migrations.AddField(
            model_name='exam',
            name='Question',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='correct_ans',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='opt1',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='opt2',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='opt3',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='opt4',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
