# Generated by Django 3.2 on 2021-05-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210522_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
